### ISSUE TITLE
User Registration

### ISSUE THREAD

**Issue by kartik-pant-23** [kartik-pant-23/IIITB-Hogwarts_Hacktoberfest#1]
In the backend on registration, we need to allot groups in such a manner that the number of members in each group is equal. Currently, groups are being assigned randomly. Also after the group is assigned, the field `numOfMembers` in Group Schema should also be incremented.

**Comment by prahasR** [comment]
@kartik-pant-23 please assign this to me

**Comment by kartik-pant-23** [comment]
> @kartik-pant-23 please assign this to me

I am assigning this to you @prahasR

**Comment by prahasR** [comment]
@kartik-pant-23 there is no `registeration.js` file in the `backend` directory of your code, But I foud it at https://github.com/kartik-pant-23/IIITB-Hogwarts/blob/master/backend/routes/registration.js. Can you please confirm is this is right file in which I have to make changes. If not then which file is needed to be changed

**Comment by kartik-pant-23** [comment]
@prahasR, that is an old repository and not well maintained, you should've gone through the code in this repository properly. Nevertheless, you need to make changes to this [file](https://github.com/kartik-pant-23/IIITB-Hogwarts_Hacktoberfest/blob/master/backend/api/controllers/users.js).

**Comment by prahasR** [comment]
@kartik-pant-23 if I use names of groups instead of _id here https://github.com/kartik-pant-23/IIITB-Hogwarts/pull/19/commits/5e1830f2e37bcb4dc9824ba5bceeb22125a69557 then would it work?

**Comment by kartik-pant-23** [comment]
**First of all, that repo is not maintained, so it is better you make changes in this repository only.**
How about making it more generic, each time a user registers, you fetch all the groups in sorted order of their `numOfMembers`, and `limit` this result to 1. All these functions are provided by `mongoose`. And this way you will just fetch the group with the least number of members.

I suggest you go through the `sort` and `limit` functions of the `mongoose` package.

**Comment by prahasR** [comment]
Ok @kartik-pant-23 I will take care of that, if I update line 22 by `Group.findOneAndUpdate({_id:minGroup[0]._id}, {noOfMembers:min_noOfMembers});` instead of `Group.findOneAndUpdate({_id:minGroup[0]._id}, {noOfMembers:min_noOfMembers+1});` will it be fine?

**Comment by kartik-pant-23** [comment]
Hey @prahasR, did you set up a database? It would be great if you can check that on your own. Though I think this should work. Also, one more remark, can you try to be consistent with the rest of the code, see how promise handling is done, somewhat like this- 
```javascript
Group.findOneAndUpdate(...)
     .then(...)
     .catch(...)
``` 
or if not like this, then at least pass a callback function to take care of any errors or exceptions- 
```javascript
Group.findOneAndUpdate({_id:minGroup[0]._id}, {noOfMembers:min_noOfMembers}, function(err, doc) {
     if(err) next(err);
     else {
          // Do rest of the work
     }
});
```
I request you to make a new PR with these changes in single commit.

**Comment by prahasR** [comment]
@kartik-pant-23 can you tell me how do I register a user, I am not able to figure out. I had set up the database and backend part.

**Comment by prahasR** [comment]
@kartik-pant-23 I find an alternative for checking my code and and did the required changes, please review.
