### ISSUE TITLE
Settings Screen UI - Mobile App

### ISSUE THREAD

**Issue by kartik-pant-23** [kartik-pant-23/IIITB-Hogwarts_Hacktoberfest#10]
Create UI for `SettingsScreen`(connecting with backend, is not yet required), it should display user's information and also allow them to add for all the fields **EXCEPT** `name`, `email`, `group`, `score`. User Schema is given below so that you can see which fields are present.
```JSON
{
  "_id":"6156b4fcbee30d1ffb3a8088",
  "name":"Test User",
  "email":"test@user.com",
  "group":"61556b0643b3c71da2e11b17",
  "score":"0",
  "about":"",
  "id_facebook":"",
  "id_instagram":"",
  "id_linkedin":"",
  "id_github":"",
  "id_twitter":"",
  "id_youtube":"",
  "id_personal":"",
}
```

**Comment by hrigved-dev** [comment]
Hey @kartik-pant-23, could you share a design to follow for this specific screen?

**Comment by kartik-pant-23** [comment]
I don't have an already made design, it would be great if you can come up with something on your own. 
Nothing much complex is required, it's enough to show static details (name, email, group) as text fields, followed by input text fields for the rest of the fields, and a button to save changes.

**Comment by TriparnoChatterjee** [comment]
Hey, @kartik-pant-23 .Can I work on this issue?

**Comment by kartik-pant-23** [comment]
If @hrigved-dev does not turn up till tomorrow, I will assign it to you @TriparnoChatterjee , till then you can have a look into other issues.

**Comment by hrigved-dev** [comment]
Please assign me this task @kartik-pant-23

**Comment by kartik-pant-23** [comment]
@hrigved-dev please find another issue, @TriparnoChatterjee is working in this.

**Comment by kartik-pant-23** [comment]
@hrigved-dev I am assigning you this issue.

**Comment by hrigved-dev** [comment]
Hey @kartik-pant-23 , due to the absence of important_strings.dart file, it is throwing error, not allowing to test.

**Comment by kartik-pant-23** [comment]
@hrigved-dev I suggest you go through the [README](https://github.com/kartik-pant-23/IIITB-Hogwarts_Hacktoberfest/blob/master/frontend/README.md) file for `frontend/`. It contains all the necessary details you need to know.

**Comment by hrigved-dev** [comment]
https://user-images.githubusercontent.com/63411663/135828846-97646b37-c5b0-4ac1-b3dc-434cb8a996fa.mp4

**Comment by hrigved-dev** [comment]
@kartik-pant-23 please let me know if any changes are required

**Comment by kartik-pant-23** [comment]
This looks great @hrigved-dev, well done. Just a few improvements I can think of are 
1. On top, for static values, instead of separate text boxes, can it be a single card showing all the information. Also, along with the group name, you can also add its logo. User details you get would look somewhat like this - 
```JSON
 {
 	"user": {
 		"name": "Test User",
 		"email": "test@user.com",
 		"group": {
 			"_id": "61556b0643b3c71da2e11b17",
 			"name": "Inventors",
 			"tagline": "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
 			"group_logo": "https://raw.githubusercontent.com/kartik-pant-23/IIITB-Hogwarts/master/assets/inventors_logo.jpg"
 		},
 		"score": 10,
 		"about": "Hi there! I am using IIITB Hogwarts.",
 		"id_facebook": "",
 		"id_instagram": "",
 		"id_linkedin": "",
 		"id_github": "",
 		"id_twitter": "",
 		"id_youtube": "",
 		"id_personal": "",
 		"_id": "615960791e2ef7e4c9e653d6",
 		"createdAt": "2021-10-03T07:49:13.621Z",
 		"updatedAt": "2021-10-03T07:49:13.621Z",
 		"__v": 0
 	}
 }
```
Please use this as dummy data and then share the screen recording.
2. Prefix icons(Company Logo) in text boxes, for Facebook, Instagram, etc. 

And really your work looks great. Kudos!!

**Comment by hrigved-dev** [comment]
Hey, thank you @kartik-pant-23, I'll make those changes and attach the screen recording!

**Comment by hrigved-dev** [comment]
https://user-images.githubusercontent.com/63411663/135855866-b9fb7420-ddef-4293-8fb3-df0e2eeff3a0.mp4

**Comment by hrigved-dev** [comment]
@kartik-pant-23 thank you for this opportunity!
