### ISSUE TITLE
Home Page UI - Mobile App

### ISSUE THREAD

**Issue by kartik-pant-23** [kartik-pant-23/IIITB-Hogwarts_Hacktoberfest#8]
Create UI for the `Dashboard`. Currently, data is being retrieved inside the `HomePageData` object. Use this to display all the groups in a list, then a horizontal list of `projects`(should be clickable and should redirect to `project_url`). Also, display the `discussion`, it should be clickable and should take to a screen where chats can be done.

**Comment by TriparnoChatterjee** [comment]
Hey, @kartik-pant-23 .Can I work on this issue?

**Comment by TriparnoChatterjee** [comment]
Hey, @kartik-pant-23 .Can I work on this issue?

**Comment by kartik-pant-23** [comment]
@TriparnoChatterjee I am assigning this to you!
